### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by gastaldi** [paulrobinson/jiralint-java#5]
I suggest to archive this repository and adopt https://gitlab.cee.redhat.com/quarkus/jira-lint instead

**Comment by paulrobinson** [comment]
I think we should keep the project open as others might want to use it. The repo you link to is private.

**Comment by gastaldi** [comment]
It's not really private but you need VPN to access it. Anyway, I'll close this then

**Comment by paulrobinson** [comment]
I was thinking anyone who uses JIRA might like to use this tool, not just people working at Red Hat.
